name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install linux build requirements
        run: sudo apt install --yes --no-install-recommends libasound2-dev pkg-config libsdl2-2.0-0 libsdl2-dev libsdl2-image-dev

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
